AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for creating a code pipeline"
Parameters:
  StackName:
    Type: String
    Default: InfraAWSCodebuild-stack
  CodeBuildCIBackendProjectName:
    Description: CI CodeBuild Project Name
    Type: String
    Default: InfraAWSCodebuild

Resources:
  SampleCloudFormationCodeBuildBackend:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref CodeBuildCIBackendProjectName
      Source:
        Type: GITHUB
        Location: https://github.com/tirula/app-java-ecs.git
        GitCloneDepth: 1
        BuildSpec: ./buildspec.yml
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
#              Pattern: ^refs/heads/feature/.*
              Pattern: ^refs/heads/main
      Environment:
        PrivilegedMode: true
        Type: LINUX_CONTAINER
        Image: aws/codebuild/standard:2.0
        ComputeType: BUILD_GENERAL1_SMALL
      ServiceRole: !Ref SampleCloudFormationCodeBuildBackendServiceRole
      Artifacts:
        Type: NO_ARTIFACTS
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: !Sub ${CodeBuildCIBackendProjectName}-CloudWatchLogs-BuildLogGroup-Name


  
  SampleCloudFormationCodeBuildBackendServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub ${CodeBuildCIBackendProjectName}-codebuild-base-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${CodeBuildCIBackendProjectName}-CloudWatchLogs-BuildLogGroup-Name
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${CodeBuildCIBackendProjectName}-CloudWatchLogs-BuildLogGroup-Name:*
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
              - Effect: Allow
                Resource:
                  - !Sub arn:aws:s3:::codepipeline-${AWS::Region}-*
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
              - Effect: Allow
                Resource:
                  - !Sub arn:aws:codebuild:::report-group-${AWS::Region}-*
                Action:
                  - codebuild:CreateReportGroup
                  - codebuild:CreateReport
                  - codebuild:UpdateReport
                  - codebuild:BatchPutTestCases
                  - codebuild:BatchPutCodeCoverages
        - PolicyName: !Sub ${CodeBuildCIBackendProjectName}-codebuild-ecr-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - "*"
                Action:
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                  - ecr:CompleteLayerUpload
                  - ecr:GetDownloadUrlForLayer
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:GetAuthorizationToken
                  - ecr-public:GetAuthorizationToken
        - PolicyName: !Sub ${CodeBuildCIBackendProjectName}-secretsmanager-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - "*"
                Action:
                  - secretsmanager:GetSecretValue

Outputs:
  SampleCloudFormationCodeBuildBackend:
    Description: CI CodeBuild Project for Backend
    Value: !Ref SampleCloudFormationCodeBuildBackend
    Export:
      Name: !Sub ${StackName}-CodeBuildBackend